### ISSUE TITLE
好像只有root功能，模块都用不了

### ISSUE THREAD

**Issue by xiaofengv233** [kindle4jerry/KernelSU_Action_nx563j#1]
rt

**Comment by kindle4jerry** [comment]
不要下载太老的 新版本应该没问题的

**Comment by kindle4jerry** [comment]
最新版本没问题
https://github.com/kindle4jerry/KernelSU_Action_nx563j/actions/runs/4215095806

**Comment by xiaofengv233** [comment]
> 最新版本没问题 https://github.com/kindle4jerry/KernelSU_Action_nx563j/actions/runs/4215095806

好的,谢谢.
