### ISSUE TITLE
刷入boot后丢失基带，无法使用WIFI和手机卡 PixelExperience

### ISSUE THREAD

**Issue by specked2527** [kindle4jerry/KernelSU_Action_nx563j#3]
**TQ1A.230105.002
PixelExperience_Plus_nx563j-13.0-20230130-0313-UNOFFICIAL**

**恢复备份boot后，基带正常使用WIFI和手机卡**
![Screenshot_2021-10-18-23-42-53](https://github.com/kindle4jerry/KernelSU_Action_nx563j/assets/124735279/c5c14970-bef1-4451-b698-9699185e7d17)
![Screenshot_20240419-103732_设置](https://github.com/kindle4jerry/KernelSU_Action_nx563j/assets/124735279/c4171e46-29bc-4424-aca6-705018cb258b)

**刷入boot后丢失基带，无法使用WIFI和手机卡**
![Screenshot_20230328-225557_设置](https://github.com/kindle4jerry/KernelSU_Action_nx563j/assets/124735279/cec5ef39-0011-42e6-8f48-80a5d40e72dd)
![Screenshot_20230328-225607_KernelSU](https://github.com/kindle4jerry/KernelSU_Action_nx563j/assets/124735279/c1fcc3ed-e6a9-4f76-82f7-ed412f76c4f1)
![Screenshot_20230328-225630_KernelSU](https://github.com/kindle4jerry/KernelSU_Action_nx563j/assets/124735279/933e8eb4-e142-49fa-842a-d785b484efb3)

**Comment by kindle4jerry** [comment]
https://github.com/kindle4jerry/KernelSU_Action_nx563j/releases
https://xdaforums.com/t/rom-unofficial-13-nx563j-pixel-experience-plus-13-for-nubia-z17.4547215/
考虑上面两个链接对着看，本项目Release版附带了测试环境，可以根据需求也试试
如果是其他系统考虑参考本项目以及你的内核源码自己搓一个，kernelsu本质就是修补内核
